site_name: Terraform Associate Certification Labs
theme:
  name: readthedocs
  language: en
  features:
    - navigation.top
    - search.highlight
    - content.code.annotate

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - tables
  - footnotes
  - def_list
  - attr_list

# https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins
# MkDocs - Diagram Integration
# MkDocs - Global
